name: Build and Release Wheels

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    container:
      image: "nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04"

    steps:
    - uses: actions/checkout@v3

    - name: Install Python ${{ matrix.python-version }}
      run: |
        apt update
        apt install -y software-properties-common
        add-apt-repository -y ppa:deadsnakes/ppa
        apt update
        apt install -y python${{ matrix.python-version }} python${{ matrix.python-version }}-distutils curl
        curl -sS https://bootstrap.pypa.io/get-pip.py | python${{ matrix.python-version }}

    - name: Install build tools
      run: python${{ matrix.python-version }} -m pip install build

    - name: Clean dist
      run: rm -rf dist

    - name: Build CPU Wheel
      run: python${{ matrix.python-version }} -m build --wheel --outdir dist/cpu

    - name: Build GPU Wheel
      run: RSPMM_WITH_CUDA=1 python${{ matrix.python-version }} -m build --wheel --outdir dist/gpu

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/cpu/*.whl
          dist/gpu/*.whl

  update-index:
    name: Update GitHub Pages Index
    needs: build-and-upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4

    - name: Generate index.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install requests
        python generate_index.py

    - name: Commit and Push index.html
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"
        git add docs/index.html
        git commit -m "🤖 Update index.html for wheels [skip ci]" || echo "No changes"
        git push
